### ISSUE TITLE
UndefinedBehaviorSanitizer failed, when serializing after using theta_a_not_b

### ISSUE THREAD

**Issue by pzhdfy** [apache/datasketches-cpp#300] opened 2022-08-29 12:20 UTC
We are integrating datasketches with Clickhouse.
In some test case, when serializing after using theta_a_not_b, we meet UndefinedBehavior(the binary built with -fsanitize=undefined). The stack.
```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../contrib/datasketches-cpp/common/include/memory_operations.hpp:51:15 in
../contrib/datasketches-cpp/common/include/memory_operations.hpp:51:15: runtime error: null pointer passed as argument 2, which is declared to never be null
#0 0x148f9160 in datasketches::copy_to_mem(void const*, void*, unsigned long) build_docker/../contrib/datasketches-cpp/common/include/memory_operations.hpp:51:3
    #1 0x148f9160 in datasketches::compact_theta_sketch_alloc<std::__1::allocator<unsigned long> >::serialize(unsigned int) const build_docker/../contrib/datasketches-cpp/theta/include/theta_sketch_impl.hpp:391:12
    #2 0x148f8849 in DB::ThetaSketchData<unsigned long>::write(DB::WriteBuffer&) const build_docker/../src/AggregateFunctions/ThetaSketchData.h:158:49
    #3 0x24aa975a in DB::SerializationAggregateFunction::serializeBinaryBulk(DB::IColumn const&, DB::WriteBuffer&, unsigned long, unsigned long) const build_docker/../src/DataTypes/Serializations/SerializationAggregateFunction.cpp:73:19
    #4 0x26fd7b85 in DB::writeData(DB::ISerialization const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&, DB::WriteBuffer&, unsigned long, unsigned long) build_docker/../src/Formats/NativeWriter.cpp:63:19
    #5 0x26fd73f2 in DB::NativeWriter::write(DB::Block const&) build_docker/../src/Formats/NativeWriter.cpp:164:13
    #6 0x26f946d4 in DB::TCPHandler::sendData(DB::Block const&) build_docker/../src/Server/TCPHandler.cpp:1742:26
    #7 0x26f90829 in DB::TCPHandler::processOrdinaryQueryWithProcessors() build_docker/../src/Server/TCPHandler.cpp:748:21
    #8 0x26f821f3 in DB::TCPHandler::runImpl() build_docker/../src/Server/TCPHandler.cpp:368:17
    #9 0x26fa22b9 in DB::TCPHandler::run() build_docker/../src/Server/TCPHandler.cpp:1866:9
    #10 0x27ee7e0b in Poco::Net::TCPServerConnection::start() build_docker/../contrib/poco/Net/src/TCPServerConnection.cpp:43:3
    #11 0x27ee82f9 in Poco::Net::TCPServerDispatcher::run() build_docker/../contrib/poco/Net/src/TCPServerDispatcher.cpp:115:20
    #12 0x2805ffe6 in Poco::PooledThread::run() build_docker/../contrib/poco/Foundation/src/ThreadPool.cpp:199:14
    #13 0x2805dace in Poco::ThreadImpl::runnableEntry(void*) build_docker/../contrib/poco/Foundation/src/Thread_POSIX.cpp:345:27
    #14 0x7fb8e0647608 in start_thread /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    #15 0x7fb8e056c132 in __clone /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

the test code can reproduce
```CXX
#include <theta_a_not_b.hpp>
#include <theta_union.hpp>

int main()
{

	datasketches::theta_union tmp_union = datasketches::theta_union::builder().build();
        datasketches::update_theta_sketch tmp_update = datasketches::update_theta_sketch::builder().build();

        datasketches::update_theta_sketch tmp_update2 = datasketches::update_theta_sketch::builder().build();

        for ( int64_t i = 0 ; i < 6144; ++i)
        {
            tmp_update2.update(&i, 8);
            if (i > 1023)
                tmp_update.update(&i, 8);
        }


            tmp_union.update(tmp_update);
            tmp_update = datasketches::update_theta_sketch::builder().build();


        datasketches::theta_a_not_b a_not_b;

            datasketches::compact_theta_sketch result = a_not_b.compute(tmp_union.get_result(), tmp_update2);
            tmp_union = datasketches::theta_union::builder().build();
            tmp_union.update(result);
            auto bytes = tmp_union.get_result().serialize();
}
```

compiler: clang15
compile_options: -g -fno-omit-frame-pointer -DSANITIZER -fsanitize=undefined -fno-sanitize-recover=all -fno-sanitize=float-divide-by-zero
link_options: -fuse-ld=lld -fsanitize=undefined

related:https://github.com/ClickHouse/ClickHouse/pull/39919

**Comment by jmalkin** [comment] 2022-08-29 16:13
Thanks for the report. We'll start investigating.

**Comment by jmalkin** [comment] 2022-08-29 16:24
@pzhdfy Can you provide the sketches version/tag or commit?

**Comment by jmalkin** [comment] 2022-08-29 20:01
Ok, was able to reproduce on linux even with the current version. We should address this, but in some sense it's a false positive: The issue is a call to memcpy to copy 0 bytes from nullptr to a valid target.

**Comment by jmalkin** [comment] 2022-08-29 21:49
Oops.. Linked after merging. This should be fixed now.

There should be some significant changes to quantiles-type sketches ready...soon. That'll trigger a major version bump, so this will be picked up in that release.

**Closed by jmalkin** 2022-08-29 21:49 UTC
